import type {Module,UserProgress} from '../types';
import {getModuleById,isModuleUnlocked} from '../data/modules';
interface Props{module:Module;completedModules:string[];progress?:UserProgress;saved:boolean;onBack:()=>void;onToggleSaved:()=>void}
function ModuleDetail({module,completedModules,progress,saved,onBack,onToggleSaved}:Props){
 const unlocked=isModuleUnlocked(module.id,completedModules);
 return <article className="module-detail"><button className="back-button" onClick={onBack}>← Voltar à trilha</button><div className="detail-heading"><div><p className="eyebrow">TEMA {module.order.toString().padStart(2,'0')} / {module.area.toUpperCase()}</p><h1><span>{module.code}</span>{module.subtitle}</h1><p>{module.theme}</p></div><button className="btn-secondary" aria-pressed={saved} onClick={onToggleSaved}>{saved?'✓ Salvo para estudar':'Salvar para estudar'}</button></div>
 <section className="content-notice"><span className="content-badge">EM PREPARAÇÃO</span><h2>Este é o plano do tema.</h2><p>A explicação, a atividade e as questões ainda serão produzidas e revisadas. Consultar este plano ou salvá-lo não conclui o módulo nem libera pré-requisitos.</p></section>
 <div className="detail-grid"><div><section className="detail-section"><p className="eyebrow">01 / OBJETIVO DA ATIVIDADE</p><h2>{module.activityType.charAt(0).toUpperCase()+module.activityType.slice(1)}</h2><p>O conteúdo seguirá uma sequência curta de explicação, prática guiada e revisão. As questões serão originais, com feedback específico para cada alternativa.</p><div className="detail-metrics"><div><b>{module.targetQuestions}</b><span>questões previstas, ainda não disponíveis</span></div><div><b>{['','Básico','Intermediário','Avançado'][module.difficulty]}</b><span>dificuldade planejada</span></div></div></section>
 <section className="detail-section"><p className="eyebrow">02 / EXPERIÊNCIA PLANEJADA</p><h2>Do conceito à decisão.</h2><ol className="learning-flow">{[['Entender','Uma explicação direta dos conceitos e dos limites do cenário.'],['Experimentar',`Atividade: ${module.activityType}.`],['Resolver','Questões por etapas, dicas opcionais e explicação dos erros.'],['Revisar','Retomar os erros e praticar com novos itens.']].map(([title,description],i)=><li key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol></section>
 <section className="detail-section"><p className="eyebrow">03 / FONTES DE APOIO</p><h2>Livros selecionados no acervo.</h2><ul className="books-list">{module.supportBooks.map(book=><li key={book}>{book}</li>)}</ul><p className="subtle">São referências de planejamento. Capítulos, versões e trechos técnicos serão conferidos ao produzir a aula.</p></section></div>
 <aside className="detail-aside"><section><p className="eyebrow">ANTES DESTE TEMA</p><h2>{unlocked?'Base inicial':'Pré-requisitos'}</h2>{module.prerequisites.length?<ul>{module.prerequisites.map(id=><li key={id}><b>{id}</b><span>{getModuleById(id)?.subtitle??id}</span><small>{completedModules.includes(id)?'Concluído':'Pendente'}</small></li>)}</ul>:<p>Este tema não exige outro módulo. Pode ser um ponto de partida da trilha.</p>}<p className="subtle">O acesso às aulas futuras dependerá dos pré-requisitos e da publicação do conteúdo.</p></section>
 <section><p className="eyebrow">CRITÉRIO DE AVANÇO PLANEJADO</p><p>Resolver 8 de 10 itens novos sem dica e explicar o raciocínio. Em segurança, completar também o procedimento do cenário sem pular etapas.</p><p className="subtle">Meta pedagógica provisória; não é nota mínima oficial do SAEP. Nenhuma avaliação está implementada nesta versão.</p></section>
 {progress&&<section><p className="eyebrow">REGISTRO ANTERIOR</p><p>Existe um registro local da versão anterior. Ele foi preservado para referência e não comprova conclusão do módulo.</p></section>}
 </aside></div></article>;
}
export default ModuleDetail;
